### ISSUE TITLE
expo router layout missing slot

### ISSUE THREAD

**Issue by SreehariJayaraj** [rajatsandeepsen/t3-turbo-biome#1]
https://github.com/rajatsandeepsen/t3-turbo-biome/blob/eb84e5eff73047a4f01a5319ee588bf95dd3eb07/apps/native/src/app/_layout.tsx#L12

I was refering your code for setting up  the expo router and I noticed a error  here , expo router states that we need to provide a slot in the root layout like children property in react for more info you can refer  [link](https://docs.expo.dev/router/layouts/)

**Comment by rajatsandeepsen** [comment]
💀

**Comment by rajatsandeepsen** [comment]
I made some changes in last 3 days.. hope it works
